#!/bin/bash
. /etc/os-release
export DEBIAN_FRONTEND=noninteractive

# --- Setup ROS 2 apt sources and keys ---
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -k > /usr/share/keyrings/ros-archive-keyring.gpg &
curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc -k | apt-key add - &
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $UBUNTU_CODENAME main" > /etc/apt/sources.list.d/ros2.list &
wait

apt-get -y update
export ROSDISTRO=${ROSDISTRO:-$("`dirname "$0"`/detect-ros-distro")}
[[ -z "$ROSDISTRO" ]] && exit 1

# --- Core ROS 2 packages ---
apt-get -y install ros-$ROSDISTRO-ros-base ros-$ROSDISTRO-rqt python3-colcon-ros python3-colcon-common-extensions python3-rosdep
apt-get -y install python3-pip python3-venv python3-sklearn python3-pandas python3-rosdep
apt-get -y install ros-$ROSDISTRO-diagnostic-updater ros-$ROSDISTRO-angles ros-$ROSDISTRO-rqt-reconfigure ros-$ROSDISTRO-rosbag2-storage-mcap
apt-get -y install libpcap-dev libpcl-dev

# --- EUFS / Simulation dependencies ---
apt-get -y install \
  ros-$ROSDISTRO-gazebo-dev \
  ros-$ROSDISTRO-rviz2 \
  ros-$ROSDISTRO-rviz-common \
  ros-$ROSDISTRO-ackermann-msgs \
  ros-$ROSDISTRO-image-geometry

# --- Initialize rosdep ---
rosdep init
