#!/bin/bash
export ROSDISTRO=${ROSDISTRO:-$("`dirname "$0"`/detect-ros-distro")}

git clone https://gitlab.com/eufs/eufs_sim &
git clone https://gitlab.com/eufs/eufs_msgs &
git clone https://gitlab.com/eufs/eufs_rviz_plugins &
if [ ! -e ~/.bashrc ] || ! grep EUFS_MASTER ~/.bashrc
then
        >>~/.bashrc cat <<-EOF
	# Added during initial setup
	alias .r='. install/setup.bash'
	alias ros2init='. /opt/ros/$ROSDISTRO/setup.bash'
	export EUFS_MASTER=$(realpath .)
	export FT_CATKIN_HOME=$(realpath ~/catkin_ws)
	export FT_COLCON_HOME=$(realpath .)
	export ROSDISTRO=$ROSDISTRO
EOF
fi &
wait

# Apply Humble Patcherino
if [[ "$ROSDISTRO" = "humble" ]]
then
	git -C eufs_sim apply $(realpath "`dirname "$0"`/diff.diff")
fi
