services:
  humble:
    entrypoint: [tail, -f, /dev/null]
    # learned/software/docker.org :: Making sure that services receive signals
    init: true
    image: mersiohw/ft-ubuntu-bootstrap:latest
    userns_mode: keep-id
    network_mode: host
    working_dir: ${HOME}
    privileged: true
    extra_hosts:
      - host.docker.internal:127.0.0.1
      - ${HOSTNAME}:127.0.0.1
    volumes:
      - ${HOME}:${HOME}
      - /etc/group:/etc/group:ro   # Group
      - /etc/passwd:/etc/passwd:ro # Uuser
      - /etc/shadow:/etc/shadow:ro # Shadow
      - /tmp/docker/:/tmp/docker/ # for the rendering cookie
      - /dev/dri:/dev/dri # direct rendering infrastructure
      - /tmp/.X11-unix:/tmp/.X11-unix # unix 🔌
      - /run/user/1000:/run/user/1000 # dbus socket, forget why it's needed
    environment: &generic-environment
      SYSTEM_ALIAS: humble
      ROS_DISTRO: humble
      ROS_DISTRO_: humble
      FT_COLCON_HOME: ${FT_COLCON_HOME:-${HOME}/ft}
      FT_CATKIN_HOME: ${FT_CATKIN_HOME:-${HOME}/catkin_ft}
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      DISPLAY: unix${DISPLAY}
      XAUTHORITY: /tmp/docker/cookie
      SHELL: /bin/zsh
    x-podman:
      uidmaps: [ 1000:10:1000 ]
