name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: base.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ft-ubuntu-bootstrap:jammy
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/ft-ubuntu-bootstrap:jammy
          cache-to: type=inline
